##登录地址
# loginUrl: 'http://www.luckybi.io/auth/login/test'
#
##挂单地址
# orderUrl: 'http://www.luckybi.io/api/ctc/order'
#
##撤单地址
# cancelOrder: 'http://www.luckybi.io/api/ctc/order/cancel'

#登录地址
 loginUrl: 'http://dev.zetafin.cn:22005/auth/login'

#挂单地址
 orderUrl: 'http://dev.zetafin.cn:22004/ctc/order'

#撤单地址
 cancelOrder: 'http://dev.zetafin.cn:22004/ctc/order/cancel'

#获取最新交易价格{api}
# priceUrl: "https://www.bitstamp.net/api/v2/ticker/btcusd/"
# bitmart: 'https://api.bitmart.com/ticker/'
# coinmarket: 'https://api.coinmarketcap.com/v2/ticker/'

 btc_usdt_url: 'https://api.coinmarketcap.com/v2/ticker/1/?convert=usdt'
 eth_btc_url: 'https://api.coinmarketcap.com/v2/ticker/1027/?convert=btc'
 eth_usdt_url: 'https://api.coinmarketcap.com/v2/ticker/1027/?convert=usdt'

#用户账号密码
 count:

  robot01: 'bu01@lanlingdai.net'
  password1: '123456Aa'
  token01: '1c591d48-843d-436b-ab40-1b9564524724'

  robot02: 'bu02@lanlingdai.net'
  password2: '123456Aa'
  token02: 'e591f8a1-9f2b-4058-9af3-fb1884507e57'

  robot03: 'eb01@lanlingdai.net'
  password3: '123456Aa'
  token03: '0b69694d-6c7c-4947-aaf7-fb465c905952'

  robot04: 'eb02@lanlingdai.net'
  password4: '123456Aa'
  token04: 'aceefbb3-7136-41c1-b907-70c037e86149'

  robot05: 'eu01@lanlingdai.net'
  password5: '123456Aa'
  token05: 'f42ab42a-2b50-4c7d-a07d-17acdc68bdc2'

  robot06: 'eu02@lanlingdai.net'
  password6: '123456Aa'
  token06: 'cbd0173d-4a86-436e-ab90-d0f7753ed27b'

  robot07: 'robot07@lanlingdai.net'
  password7: '123456Aa'

  robot08: 'robot08@lanlingdai.net'
  password8: '123456Aa'

  robot09: 'robot09@lanlingdai.net'
  password9: '123456Aa'

  robot10: 'robot10@lanlingdai.net'
  password10: '123456Aa'

  robot11: 'robot11@lanlingdai.net'
  password11: '123456Aa'

  robot12: 'robot12@lanlingdai.net'
  password12: '123456Aa'

  robot13: 'robot13@lanlingdai.net'
  password13: '123456Aa'

  robot14: 'robot14@lanlingdai.net'
  password14: '123456Aa'

  robot15: 'robot15@lanlingdai.net'
  password15: '123456Aa'

  robot16: 'robot16@lanlingdai.net'
  password4: '123456Aa'

  robot17: 'robot17@lanlingdai.net'
  password5: '123456Aa'

  robot18: 'robot18@lanlingdai.net'
  password6: '123456Aa'

  robot19: 'robot19@lanlingdai.net'
  password19: '123456Aa'

  robot20: 'robot20@lanlingdai.net'
  password20: '123456Aa'

  robot21: 'robot21@lanlingdai.net'
  password21: '123456Aa'

  robot22: 'robot22@lanlingdai.net'
  password22: '123456Aa'

  robot23: 'robot23@lanlingdai.net'
  password23: '123456Aa'

  robot24: 'robot24@lanlingdai.net'
  password24: '123456Aa'

#交易对
 tradePair:

  usdt_btc_pairCode: 'btc_usdt'
  btc_usdtMaxCount: 0.04

  usdt_eth_pairCode: 'eth_usdt'
  eth_usdtMaxCount: 0.01

  btc_eth_pairCode: 'eth_btc'
  eth_btcMaxCount: 0.6

#货币对应id
 btc: 1
 eth: 1027
 xrp: 52
 bch: 1831
 eos: 1765
 ltc: 2
 ada: 2010
 xlm: 512
 iota: 1720




